export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS"
export const USER_LOGGED_IN = "USER_LOGGED_IN"
export const USER_LOGGED_OUT = "USER_LOGGED_OUT"

// export const SIGN_IN = "SIGN_IN"

export const ADD_SINGLE_APPOINNTMENT = "ADD_SINGLE_APPOINNTMENT"

export const ADD_ALL_APPOINNTMENT = "ADD_ALL_APPOINNTMENT"

export const SET_APPOINTMENT_STATUS = "SET_APPOINTMENT_STATUS"

export const ADD_ALL_DOCTORS = 'ADD_ALL_DOCTORS'