export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS"

// export const SIGN_IN = "SIGN_IN"

export const ADD_SINGLE_APPOINNTMENT = "ADD_SINGLE_APPOINNTMENT"

export const ADD_ALL_APPOINNTMENT = "ADD_ALL_APPOINNTMENT"

export const SET_APPOINTMENT_STATUS = "SET_APPOINTMENT_STATUS"